### ISSUE TITLE
Filter button on client application does not work

### ISSUE THREAD

**Issue by rahme-butaineh** [Call-for-Code-for-Racial-Justice/Truth-Loop#108] opened 2021-02-19 18:54 UTC
The filter button on the top right corner of the client application is not clickable. Should open pop-up modal to allow user to filter legislation by different fields.

**Comment by felizj17** [comment] 2021-09-22 23:21
hey, started working on this, what should the filters be? Using 'filter1' as a filler for now.  
![filterModal-snip](https://user-images.githubusercontent.com/37090868/134434275-b1fabec8-562b-4ff0-ad1d-c8082dc4e660.png)
w.

**Comment by felizj17** [comment] 2021-09-29 18:12
https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/pull/170 pr was merged regarding this issue

**Comment by markstur** [comment] 2021-09-29 20:07
Good start, but I think the issue is still open since filter1..filter5 checkboxes isn't really functionally complete for policy filters.  If we have a separate issue for that somewhere, I can close this.  Leaving open for now.

**Comment by felizj17** [comment] 2021-09-29 20:56
Alright, do you know what the filters should be? by legislation number, or by community approval.  if there was a little more context I would be able to work on this.

**Comment by markstur** [comment] 2021-09-29 21:48
Trying our slack channel to see if we have anything describing the filter functionality: https://callforcode.slack.com/archives/C01CUD71V0S/p1632952064038700?thread_ts=1632951602.038300&cid=C01CUD71V0S

**Comment by demilolu** [comment] 2021-10-01 19:50
closed, solved by #170.
 continuing work with #175

**Closed by demilolu** 2021-10-01 19:50 UTC
Labels: bug, enhancement, help wanted, hacktoberfest
